# -*- coding: utf-8 -*-
"""attrition_colab.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19MPjVcfRdZ1BQ-ZC8klKC5RNaoh8jTUV

# Прогнозирование оттока сотрудников Альфа-Банка
## Курсовая работа: Цифровой продукт для HR-специалистов на основе машинного обучения

**Цель:** разработать ML-модель, которая еженедельно оценивает вероятность увольнения
каждого сотрудника в следующем месяце и объясняет ключевые факторы риска.

**Методология:**
1. Загрузка и очистка данных, детальный EDA
2. Feature Engineering (event-признаки, chaos-индексы, лаги, эффект домино)
3. Time-based split (обучение на прошлом, тест на будущем)
4. Базовые модели: LogReg, DecisionTree, RandomForest, XGBoost, LightGBM
5. TimeSeriesSplit CV + проверка переобучения (train vs test ROC-AUC)
6. Optuna-оптимизация LightGBM + SMOTE
7. Выбор порога по F1, SHAP-интерпретация, HR-скоринг
"""

!pip install lightgbm xgboost optuna shap imbalanced-learn --quiet

# Commented out IPython magic to ensure Python compatibility.
import warnings, gc
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import TimeSeriesSplit
from sklearn.metrics import (
    roc_auc_score, average_precision_score,
    f1_score, recall_score, precision_score,
    classification_report, confusion_matrix,
    roc_curve, precision_recall_curve,
)

import lightgbm as lgb
import xgboost as xgb
import optuna
optuna.logging.set_verbosity(optuna.logging.WARNING)
import shap
from imblearn.over_sampling import SMOTE

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

"""## 1. Конфигурация"""

DATA       = "Отток_train.csv"
TARGET     = "flg_fire_next_month"
TEST_START = "2024-09-01"

EVENT_COLS = [
    "employee_headadmin_uk_change",
    "employee_headfunc_uk_change",
    "division_uk_change",
    "salesplace_name_change",
    "staffing_name_change",
]

print(f"Конфигурация: TARGET={TARGET}, TEST_START={TEST_START}")

"""## 2. Загрузка и очистка данных

- amount_* хранятся как числа/строки — конвертация через pd.to_numeric
- Признаки с долей NaN > 95% удаляются
- hire_date < 0 (2 строки, вероятно фиксация невыхода на работу), поэтому переводим в NaN
"""

df = pd.read_csv(DATA, low_memory=False)
df["dt"] = pd.to_datetime(df["dt"], errors="coerce")
df = df.dropna(subset=["dt"]).sort_values(["employee_id","dt"]).reset_index(drop=True)
df[TARGET] = pd.to_numeric(df[TARGET], errors="coerce").fillna(0).astype(int)

print(f"Загружено: {df.shape}")
print(f"Период наблюдения: {df['dt'].min().date()} — {df['dt'].max().date()}")
print(f"Уникальных сотрудников: {df['employee_id'].nunique():,}")
print(f"Количество недель: {df['dt'].nunique()}")

df.head(3)

df.info()

# Конвертация amount_* в float
for col in [c for c in df.columns if c.startswith("amount_")]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

amount_cols    = [c for c in df.columns if c.startswith("amount_")]
null_pct       = df[amount_cols].isnull().mean()
drop_high_null = null_pct[null_pct > 0.95].index.tolist()
df.drop(columns=drop_high_null, inplace=True)
print(f"Удалены amount-признаки с NaN > 95%: {drop_high_null}")

# hire_date < 0 — фиксируем как аномалию, не удаляем строки
n_negative_hire = (pd.to_numeric(df["hire_date"], errors="coerce") < 0).sum()
print(f"Строк с hire_date < 0: {n_negative_hire} (вероятно, фиксация невыхода на работу)")

# divconet_name — проверка на константу
print(f"\ndivconet_name уникальных значений: {df['divconet_name'].nunique()}")
if df["divconet_name"].nunique() <= 1:
    df.drop(columns=["divconet_name"], inplace=True)
    print("divconet_name удалён как константа")

"""## 3. Разведочный анализ данных (EDA)

### 3.1 Целевая переменная и дисбаланс классов
"""

vc        = df[TARGET].value_counts().reindex([0,1], fill_value=0)
pos_rate  = df[TARGET].mean()
ratio     = vc[0] / max(vc[1], 1)

print(f"Целевая переменная flg_fire_next_month:")
print(f"  flg=0: {vc[0]:,} ({(1-pos_rate)*100:.2f}%)")
print(f"  flg=1: {vc[1]:,} ({pos_rate*100:.2f}%)")
print(f"  Дисбаланс: {ratio:.0f}:1")

# Агрегация на уровень сотрудника
ever_fire = df.groupby("employee_id")[TARGET].max()
print(f"\nНа уровне сотрудников ({ever_fire.count():,} человек):")
print(f"  Хотя бы раз flg=1: {ever_fire.sum():,} ({ever_fire.mean()*100:.1f}%)")
print(f"  Это соответствует реальному годовому уровню текучести в банковском ритейле (~16%)")

plt.figure(figsize=(6, 6))
plt.pie([vc[0], vc[1]], labels=["Остался","Уволится"], autopct="%1.2f%%",
        colors=["#F03024","#C5C6C7"], startangle=90)
plt.title(f"Распределение целевой переменной (по строкам)\nДисбаланс {ratio:.0f}:1")
plt.show()

"""### 3.2 Временные паттерны: аномальные пики оттока"""

weekly = df.groupby("dt")[TARGET].agg(total="count", fired="sum", rate=lambda x: x.mean()*100)
print("Топ-5 недель по доле оттока:")
print(weekly.sort_values("rate", ascending=False).head(5).to_string())

plt.figure(figsize=(14, 4))
plt.plot(weekly.index, weekly["rate"], marker="o", ms=3, lw=1.5, color="#2E6DA4")
plt.axhline(pos_rate*100, color="red", ls="--", lw=1, label=f"Среднее ({pos_rate*100:.2f}%)")
plt.axvline(pd.to_datetime(TEST_START), color="blue", ls="--", lw=1.5, label="Граница train/test")
plt.title("Недельная динамика оттока — аномальные пики в начале периода (январь-февраль)")
plt.xlabel("Дата среза"); plt.ylabel("% flg=1")
plt.legend(); plt.grid(True, alpha=0.3)
plt.show()

anomaly_weeks = weekly[weekly["rate"] > 3]
print(anomaly_weeks.to_string())

"""### 3.3 Характеристики сотрудников: возраст, стаж, пол"""

age_yrs    = pd.to_numeric(df["birth_date"], errors="coerce") / 365.25
tenure_yrs = pd.to_numeric(df["hire_date"],  errors="coerce").clip(lower=0) / 365.25

print("Возраст (лет):")
print(f"  Медиана: {age_yrs.median():.1f}  Диапазон: [{age_yrs.min():.1f}, {age_yrs.max():.1f}]")
for t in [0, 1]:
    s = age_yrs[df[TARGET]==t]
    print(f"  flg={t}: медиана={s.median():.1f}  среднее={s.mean():.1f}")

print("\nСтаж (лет):")
print(f"  Медиана: {tenure_yrs.median():.2f}  Максимум: {tenure_yrs.max():.1f}")
for t in [0, 1]:
    s = tenure_yrs[df[TARGET]==t]
    print(f"  flg={t}: медиана={s.median():.2f}  среднее={s.mean():.2f}")

print("\nПол (gender_ccode):")
gender_counts = df["gender_ccode"].value_counts(normalize=True) * 100
print(gender_counts.round(1).to_string())
for g in df["gender_ccode"].dropna().unique():
    rate = df[df["gender_ccode"]==g][TARGET].mean() * 100
    print(f"  Частота оттока, {g}: {rate:.2f}%")

fig, axes = plt.subplots(1, 2, figsize=(13, 4))
for t, c, l in [(0,"#2E6DA4","flg=0"), (1,"#C0392B","flg=1")]:
    axes[0].hist(age_yrs[df[TARGET]==t].dropna(), bins=40, alpha=0.6, color=c, label=l, density=True)
    axes[1].hist(tenure_yrs[df[TARGET]==t].dropna(), bins=40, alpha=0.6, color=c, label=l, density=True)
axes[0].set(title="Возраст по классам", xlabel="Лет", ylabel="Плотность")
axes[1].set(title="Стаж по классам", xlabel="Лет")
for ax in axes:
    ax.legend(); ax.grid(True, alpha=0.3)
plt.tight_layout()
plt.show()

"""### 3.4 Отток по бизнес-линиям"""

biz_stats = df.groupby("staffbusinessline_name")[TARGET].agg(
    rows="count", fired="sum", rate=lambda x: x.mean()*100
).sort_values("rate", ascending=False)
print("Частота оттока по бизнес-линиям:")
print(biz_stats.round(2).to_string())

plt.figure(figsize=(9, 5))
biz_stats["rate"].sort_values().plot(kind="barh", color="#2E6DA4")
plt.xlabel("% оттока"); plt.title("Частота оттока по бизнес-линиям")
plt.grid(True, axis="x", alpha=0.3)
plt.tight_layout()
plt.show()

"""### 3.5 Event-признаки: организационные изменения"""

print(f"{'Признак':<35} {'Доля -1':>10}  {'Медиана дней':>14}  {'Среднее дней':>14}")
for col in EVENT_COLS:
    vals = pd.to_numeric(df[col], errors="coerce")
    neg1_share = (vals == -1).mean() * 100
    days = vals[vals > 0]
    print(f"  {col:<33} {neg1_share:>9.1f}%  {days.median():>14.0f}  {days.mean():>14.0f}")

print(f"\nСвязь event-признаков с увольнением (доля строк с событием != -1):")
for col in EVENT_COLS:
    vals = pd.to_numeric(df[col], errors="coerce")
    h0 = (vals[df[TARGET]==0] != -1).mean() * 100
    h1 = (vals[df[TARGET]==1] != -1).mean() * 100
    print(f"  {col:<35} flg=0: {h0:>5.1f}%   flg=1: {h1:>5.1f}%   Δ={h1-h0:+.1f}%")

"""### 3.6 Руководители (ФР/АР): покрытие и связь со стажем"""

fr_missing = df["fr_gender_ccode"].isnull().mean() * 100
ar_missing = df["ar_gender_ccode"].isnull().mean() * 100
print(f"Отсутствует ФР: {fr_missing:.1f}% строк")
print(f"Отсутствует АР: {ar_missing:.1f}% строк")

fr_tenure = pd.to_numeric(df["fr_hire_date"], errors="coerce").clip(lower=0) / 365.25
print(f"\nСтаж функционального руководителя (ФР):")
print(f"  Медиана: {fr_tenure.median():.2f} лет  Среднее: {fr_tenure.mean():.2f} лет")
for t in [0, 1]:
    s = fr_tenure[df[TARGET]==t]
    print(f"  flg={t}: медиана={s.median():.2f}  среднее={s.mean():.2f}")

"""### 3.7 Amount-признаки: покрытие и корреляция с target"""

amount_cols = [c for c in df.columns if c.startswith("amount_")]
amount_info = []
for col in amount_cols:
    s   = df[col]
    cov = s.notnull().mean() * 100
    corr = df[TARGET].corr(s, method="spearman")
    amount_info.append({"признак": col, "покрытие_%": round(cov,1), "spearman": round(corr,4)})

amount_df = pd.DataFrame(amount_info).sort_values("покрытие_%", ascending=False)
print("Amount-признаки — покрытие и корреляция с целевой переменной:")
print(amount_df.to_string(index=False))

print(f"\nМаксимальная |корреляция|: {amount_df['spearman'].abs().max():.4f}")

HIGH_COV = amount_df[amount_df["покрытие_%"] > 50]["признак"].tolist()
print(f"\nПризнаки с покрытием >50% ({len(HIGH_COV)} шт.): {HIGH_COV}")

"""### 3.8 Корреляционный анализ числовых признаков"""

corr_cols = ["birth_date","hire_date","fr_birth_date","fr_hire_date",
             "ar_birth_date","ar_hire_date"] + HIGH_COV[:6]
corr_cols = [c for c in corr_cols if c in df.columns]
corr_matrix = df[corr_cols].apply(pd.to_numeric, errors="coerce").corr(method="pearson")

plt.figure(figsize=(10, 8))
sns.heatmap(corr_matrix, annot=True, fmt=".2f", cmap="coolwarm", center=0,
            square=True, linewidths=0.5, cbar_kws={"shrink": 0.8})
plt.title("Матрица корреляций Пирсона (основные числовые признаки)")
plt.tight_layout()
plt.show()

print("Ключевые наблюдения:")
print(f"  birth_date ↔ hire_date: r = {corr_matrix.loc['birth_date','hire_date']:.3f}")
if "fr_birth_date" in corr_matrix.columns:
    print(f"  fr_birth_date ↔ fr_hire_date: r = {corr_matrix.loc['fr_birth_date','fr_hire_date']:.3f}")
if "ar_birth_date" in corr_matrix.columns:
    print(f"  ar_birth_date ↔ ar_hire_date: r = {corr_matrix.loc['ar_birth_date','ar_hire_date']:.3f}")

"""## 4. Feature Engineering

- -1 в event-признаках означает «события не было» — расщепляем на _flag (было/не было) и _days_log (давность события)
- Возраст и стаж переводятся из дней в годы
- Индекс хаоса: количество организационных изменений за последние 90 дней
- Эффект домино: число уволившихся коллег по бизнес-линии за последние 4 недели
- Разрывы в стаже/возрасте между сотрудником и руководителями
- Все агрегаты строятся **внутри групп по employee_id** с сортировкой по дате — без утечки данных между сотрудниками
"""

df = df.sort_values(["employee_id","dt"]).reset_index(drop=True)
grp = df.groupby("employee_id", sort=False)

# 1. Порядковый номер наблюдения сотрудника
df["weeks_observed"] = grp.cumcount()

# 2. Возраст и стаж → годы (отрицательный стаж → NaN, без удаления строк)
for prefix in ["","fr_","ar_"]:
    bd, hd = prefix+"birth_date", prefix+"hire_date"
    if bd in df.columns:
        df[prefix+"age_yrs"] = pd.to_numeric(df[bd], errors="coerce") / 365.25
    if hd in df.columns:
        raw = pd.to_numeric(df[hd], errors="coerce")
        df[prefix+"tenure_yrs"] = raw.clip(lower=0) / 365.25
        df.loc[raw < 0, prefix+"tenure_yrs"] = np.nan

# 3. Признаки по стажу
df["tenure_bucket"] = pd.cut(
    df["tenure_yrs"].fillna(-1),
    bins=[-2, 0, 0.5, 1, 2, 3, 5, 10, 100],
    labels=[0,1,2,3,4,5,6,7]).astype(float)
df["tenure_lt1"] = (df["tenure_yrs"].fillna(99) < 1).astype(float)

# 4. Пол → бинарный
for col in ["gender_ccode","fr_gender_ccode","ar_gender_ccode"]:
    if col in df.columns:
        df[col] = (df[col].astype(str).str.strip() == "М").astype(float)

# 5. Разрывы со руководителями
for pfx, label in [("fr_","fr"),("ar_","ar")]:
    for attr in ["age_yrs","tenure_yrs"]:
        e_col, m_col = attr, pfx+attr
        if e_col in df.columns and m_col in df.columns:
            df[f"gap_{label}_{attr}"] = df[m_col] - df[e_col]

# 6. Временные признаки
df["month"]   = df["dt"].dt.month
df["quarter"] = df["dt"].dt.quarter

# 7. Event-признаки: flag + days_log
all_events = EVENT_COLS + ["fr_"+e for e in EVENT_COLS] + ["ar_"+e for e in EVENT_COLS]
for col in all_events:
    if col not in df.columns: continue
    vals = pd.to_numeric(df[col], errors="coerce").fillna(-1)
    df[col+"_flag"]     = (vals > 0).astype(float)
    df[col+"_recent_90"] = ((vals > 0) & (vals <= 90)).astype(float)
    df[col+"_days_log"] = np.log1p(vals.clip(lower=0))

# 8. Индекс-хаоса (организационная нестабильность, изменения в коллективе)
for label, events in {"employee": EVENT_COLS,
                      "fr": ["fr_"+e for e in EVENT_COLS],
                      "ar": ["ar_"+e for e in EVENT_COLS]}.items():
    cols90 = [e+"_recent_90" for e in events if e+"_recent_90" in df.columns]
    df[f"chaos_{label}"] = df[cols90].sum(axis=1) if cols90 else 0.0
df["chaos_total"] = df["chaos_employee"] + df["chaos_fr"] + df["chaos_ar"]

# 9. Конкретные триггеры
adm_days = "employee_headadmin_uk_change_days_log"
if adm_days in df.columns:
    raw_adm = pd.to_numeric(df["employee_headadmin_uk_change"], errors="coerce")
    df["new_manager_recent_30"] = ((raw_adm > 0) & (raw_adm <= 30)).astype(float)

frf_days = "fr_employee_headfunc_uk_change"
if frf_days in df.columns:
    raw_frf = pd.to_numeric(df[frf_days], errors="coerce")
    df["fr_func_changed_60"] = ((raw_frf > 0) & (raw_frf <= 60)).astype(float)

# 10. Лаговые и скользящиепризнаки (по 27 ключевым: amount>50% покрытия, *_days, tenure_yrs)
lag_base = [c for c in HIGH_COV] + [c+"_days_log" for c in EVENT_COLS if c+"_days_log" in df.columns] + ["tenure_yrs"]
lag_base = [c for c in lag_base if c in df.columns]

for col in lag_base:
    df[col+"_lag1w"] = grp[col].shift(1)
    df[col+"_lag4w"] = grp[col].shift(4)
    df[col+"_roll4w"] = grp[col].transform(lambda x: x.shift(1).rolling(4, min_periods=1).mean())
    df[col+"_delta4w"] = df[col] - grp[col].shift(4)

# 11. Эффект домино — увольнения коллег по бизнес-линии
df = df.sort_values(["staffbusinessline_name","dt"])
df["colleagues_fired_last_4w"] = (
    df.groupby("staffbusinessline_name")[TARGET]
    .transform(lambda x: x.shift(1).rolling(4, min_periods=1).sum())
    .fillna(0))
df = df.sort_values(["employee_id","dt"]).reset_index(drop=True)

gc.collect()
print(f"\nИтоговый размер после FE: {df.shape}")
print(f"Признаков создано: {df.shape[1] - 28}")

"""## 5. Разделение данных - Time-Based Split

Обучение на данных **до** TEST_START, тест — **после**. Это имитирует
реальную эксплуатацию: модель обучена на прошлом, оценивается на будущем
"""

mask_tr = df["dt"] < pd.to_datetime(TEST_START)
mask_te = df["dt"] >= pd.to_datetime(TEST_START)

print(f"Граница: {TEST_START}")
print(f"Train: {mask_tr.sum():,} строк ({df.loc[mask_tr,'dt'].min().date()} → {df.loc[mask_tr,'dt'].max().date()})")
print(f"Test:  {mask_te.sum():,} строк ({df.loc[mask_te,'dt'].min().date()} → {df.loc[mask_te,'dt'].max().date()})")
print(f"Train flg=1: {df.loc[mask_tr,TARGET].sum():,} ({df.loc[mask_tr,TARGET].mean()*100:.2f}%)")
print(f"Test  flg=1: {df.loc[mask_te,TARGET].sum():,} ({df.loc[mask_te,TARGET].mean()*100:.2f}%)")

assert mask_tr.sum() > 0 and mask_te.sum() > 0, "ОШИБКА: train или test пустой"
assert df.loc[mask_tr,TARGET].nunique() == 2 and df.loc[mask_te,TARGET].nunique() == 2, \
       "ОШИБКА: в одной из выборок только один класс"


# OHE для staffbusinessline_name
tc   = df.loc[mask_tr,"staffbusinessline_name"].value_counts()
rare = tc[tc < 200].index
df["staffbusinessline_name"] = df["staffbusinessline_name"].where(
    ~df["staffbusinessline_name"].isin(rare), "Прочее")
train_cats = sorted(df.loc[mask_tr,"staffbusinessline_name"].dropna().unique())
df["staffbusinessline_name"] = pd.Categorical(df["staffbusinessline_name"], categories=train_cats)
df = pd.get_dummies(df, columns=["staffbusinessline_name"], drop_first=True, dtype=float)

DROP = [TARGET,"employee_id","dt","birth_date","hire_date",
        "fr_birth_date","fr_hire_date","ar_birth_date","ar_hire_date"] + \
       EVENT_COLS + ["fr_"+e for e in EVENT_COLS] + ["ar_"+e for e in EVENT_COLS]
FEAT = [c for c in df.columns if c not in DROP and df[c].dtype != object]

med = df.loc[mask_tr, FEAT].median()
X_tr = df.loc[mask_tr, FEAT].fillna(med).reset_index(drop=True)
X_te = df.loc[mask_te, FEAT].fillna(med).reset_index(drop=True)
y_tr = df.loc[mask_tr, TARGET].reset_index(drop=True)
y_te = df.loc[mask_te, TARGET].reset_index(drop=True)

print(f"\nПризнаков (после FE и OHE): {len(FEAT)}")
print(f"X_tr: {X_tr.shape}  X_te: {X_te.shape}")
print(f"NaN в X_tr: {X_tr.isnull().sum().sum()}  NaN в X_te: {X_te.isnull().sum().sum()}")

SCALE_POS = float((y_tr==0).sum() / max((y_tr==1).sum(),1))
print(f"scale_pos_weight: {SCALE_POS:.1f}")

del df; gc.collect()

scaler  = StandardScaler()
X_tr_sc = scaler.fit_transform(X_tr)
X_te_sc = scaler.transform(X_te)

"""## 6. Базовые модели

Пять моделей с фиксированными (не оптимизированными) гиперпараметрами —
baseline для последующего сравнения с Optuna-оптимизацией.

Метрики: **ROC-AUC**, **PR-AUC** (основная при дисбалансе), **F1, Recall, Precision** при пороге 0,5
"""

results = []
models  = {}

def eval_model(name, m, Xtr, Xte):
    m.fit(Xtr, y_tr)
    prob = m.predict_proba(Xte)[:,1]
    pred = m.predict(Xte)
    r = {"model": name,
         "ROC_AUC":   round(roc_auc_score(y_te, prob), 4),
         "PR_AUC":    round(average_precision_score(y_te, prob), 4),
         "F1":        round(f1_score(y_te, pred, zero_division=0), 4),
         "Recall":    round(recall_score(y_te, pred, zero_division=0), 4),
         "Precision": round(precision_score(y_te, pred, zero_division=0), 4)}
    models[name] = (m, Xte)
    results.append(r)
    print(f"  {name:<22} ROC={r['ROC_AUC']}  PR={r['PR_AUC']}  "
          f"F1={r['F1']}  Recall={r['Recall']}  Precision={r['Precision']}")
    return r

print("Обучение базовых моделей:\n")

eval_model("LogReg",
    LogisticRegression(C=0.1, max_iter=2000, class_weight="balanced",
                       random_state=RANDOM_STATE, n_jobs=-1),
    X_tr_sc, X_te_sc)

eval_model("DecisionTree",
    DecisionTreeClassifier(max_depth=8, min_samples_leaf=20,
                           class_weight="balanced", random_state=RANDOM_STATE),
    X_tr, X_te)

eval_model("RandomForest",
    RandomForestClassifier(n_estimators=200, max_depth=12, min_samples_leaf=10,
                           class_weight="balanced", n_jobs=-1, random_state=RANDOM_STATE),
    X_tr, X_te)
gc.collect()

eval_model("XGBoost",
    xgb.XGBClassifier(n_estimators=400, learning_rate=0.05, max_depth=6,
                       scale_pos_weight=SCALE_POS, tree_method="hist",
                       eval_metric="aucpr", random_state=RANDOM_STATE,
                       n_jobs=-1, verbosity=0),
    X_tr, X_te)
gc.collect()

eval_model("LightGBM",
    lgb.LGBMClassifier(n_estimators=400, learning_rate=0.05, max_depth=6,
                       is_unbalance=True, random_state=RANDOM_STATE,
                       n_jobs=-1, verbose=-1),
    X_tr, X_te)
gc.collect()

res_df = pd.DataFrame(results).set_index("model")
print(res_df.to_string())

"""## 7. Кросс-валидация и проверка переобучения"""

tscv = TimeSeriesSplit(n_splits=5)
cv_results = {}

model_defs = {
    "LogReg": LogisticRegression(C=0.1, max_iter=2000, class_weight="balanced",
                                 random_state=RANDOM_STATE, n_jobs=-1),
    "DecisionTree": DecisionTreeClassifier(max_depth=8, min_samples_leaf=20,
                                           class_weight="balanced", random_state=RANDOM_STATE),
    "RandomForest": RandomForestClassifier(n_estimators=200, max_depth=12, min_samples_leaf=10,
                                           class_weight="balanced", n_jobs=-1, random_state=RANDOM_STATE),
    "XGBoost": xgb.XGBClassifier(n_estimators=400, learning_rate=0.05, max_depth=6,
                                  scale_pos_weight=SCALE_POS, tree_method="hist",
                                  eval_metric="aucpr", random_state=RANDOM_STATE, n_jobs=-1, verbosity=0),
    "LightGBM": lgb.LGBMClassifier(n_estimators=400, learning_rate=0.05, max_depth=6,
                                    is_unbalance=True, random_state=RANDOM_STATE, n_jobs=-1, verbose=-1),
}

print("TimeSeriesSplit (5 фолдов) — средний CV ROC-AUC:\n")
for name, model in model_defs.items():
    Xtr_use = X_tr_sc if name == "LogReg" else X_tr.values
    fold_aucs = []
    for fold_idx, (tr_idx, va_idx) in enumerate(tscv.split(Xtr_use)):
        m = type(model)(**model.get_params())
        m.fit(Xtr_use[tr_idx], y_tr.iloc[tr_idx])
        prob = m.predict_proba(Xtr_use[va_idx])[:,1]
        if y_tr.iloc[va_idx].nunique() == 2:
            fold_aucs.append(roc_auc_score(y_tr.iloc[va_idx], prob))
    cv_results[name] = np.mean(fold_aucs) if fold_aucs else np.nan
    print(f"  {name:<15} CV ROC-AUC = {cv_results[name]:.4f}  (фолдов: {len(fold_aucs)})")
    gc.collect()

# Проверка переобучения: Train vs Test ROC-AUC
print("\nПроверка переобучения (Train vs Test ROC-AUC):\n")
overfit_results = []
for name in res_df.index:
    m, _ = models[name]
    Xtr_use = X_tr_sc if name == "LogReg" else X_tr
    train_prob = m.predict_proba(Xtr_use)[:,1]
    train_auc  = roc_auc_score(y_tr, train_prob)
    test_auc   = res_df.loc[name, "ROC_AUC"]
    gap        = train_auc - test_auc
    overfit_results.append({"model": name, "Train_AUC": round(train_auc,4),
                            "Test_AUC": test_auc, "Delta": round(gap,4)})
    flag = "переобучение" if gap > 0.10 else "переобучения нет"
    print(f"  {name:<15} Train={train_auc:.4f}  Test={test_auc:.4f}  Δ={gap:.4f}  {flag}")

overfit_df = pd.DataFrame(overfit_results).set_index("model")
print(f"признаков ({len(FEAT)}) относительно количества положительных примеров")
print(f"в train ({y_tr.sum():,}).")

"""## 8. Optuna-оптимизация LightGBM + SMOTE"""

cut_val = X_tr.index[int(len(X_tr)*0.9)]
Xvtr, Xvva = X_tr.iloc[:cut_val], X_tr.iloc[cut_val:]
yvtr, yvva = y_tr.iloc[:cut_val], y_tr.iloc[cut_val:]
print(f"Внутренняя валидация: train={len(Xvtr):,}  val={len(Xvva):,}  val_pos={yvva.sum():,}")

def lgb_objective(trial):
    params = dict(
        n_estimators      = trial.suggest_int("n_estimators", 200, 700),
        learning_rate     = trial.suggest_float("learning_rate", 0.01, 0.2, log=True),
        max_depth         = trial.suggest_int("max_depth", 4, 8),
        num_leaves        = trial.suggest_int("num_leaves", 20, 150),
        subsample         = trial.suggest_float("subsample", 0.6, 1.0),
        colsample_bytree  = trial.suggest_float("colsample_bytree", 0.6, 1.0),
        min_child_samples = trial.suggest_int("min_child_samples", 5, 100),
        reg_alpha         = trial.suggest_float("reg_alpha", 1e-3, 10, log=True),
        reg_lambda        = trial.suggest_float("reg_lambda", 1e-3, 10, log=True),
        is_unbalance=True, random_state=RANDOM_STATE, n_jobs=-1, verbose=-1,
    )
    m = lgb.LGBMClassifier(**params)
    m.fit(Xvtr, yvtr)
    return average_precision_score(yvva, m.predict_proba(Xvva)[:,1])

study = optuna.create_study(direction="maximize",
                             sampler=optuna.samplers.TPESampler(seed=RANDOM_STATE))
study.optimize(lgb_objective, n_trials=60, show_progress_bar=True)

best_params = study.best_params
best_params.update({"is_unbalance":True, "random_state":RANDOM_STATE, "n_jobs":-1, "verbose":-1})
print(f"\nBest val PR-AUC: {study.best_value:.4f}")
print(f"Best params: {best_params}")

eval_model("LightGBM_opt", lgb.LGBMClassifier(**best_params), X_tr, X_te)
gc.collect()

# SMOTE
minority_n = int((y_tr==1).sum())
k_neighbors = max(1, min(5, minority_n - 1))
target_ratio = 0.05

sm = SMOTE(random_state=RANDOM_STATE, k_neighbors=k_neighbors, sampling_strategy=target_ratio)
X_sm, y_sm = sm.fit_resample(X_tr, y_tr)
print(f"После SMOTE: {X_sm.shape}, доля flg=1: {y_sm.mean()*100:.2f}%")

smote_params = {k:v for k,v in best_params.items() if k != "is_unbalance"}
lgb_smote = lgb.LGBMClassifier(**smote_params, is_unbalance=False)
lgb_smote.fit(X_sm, y_sm)

prob_sm = lgb_smote.predict_proba(X_te)[:,1]
pred_sm = lgb_smote.predict(X_te)
r_sm = {"model": "LightGBM_SMOTE",
        "ROC_AUC":   round(roc_auc_score(y_te, prob_sm), 4),
        "PR_AUC":    round(average_precision_score(y_te, prob_sm), 4),
        "F1":        round(f1_score(y_te, pred_sm, zero_division=0), 4),
        "Recall":    round(recall_score(y_te, pred_sm, zero_division=0), 4),
        "Precision": round(precision_score(y_te, pred_sm, zero_division=0), 4)}
models["LightGBM_SMOTE"] = (lgb_smote, X_te)
results.append(r_sm)
print(f"\n  LightGBM_SMOTE   ROC={r_sm['ROC_AUC']}  PR={r_sm['PR_AUC']}  "
      f"F1={r_sm['F1']}  Recall={r_sm['Recall']}  Precision={r_sm['Precision']}")
print("\nСравнение с LightGBM_opt (без SMOTE) показывает, насколько")
print("class_weight/is_unbalance уже достаточен для коррекции дисбаланса.")
del X_sm, y_sm; gc.collect()

"""## 9. Итоговая таблица и выбор оптимального порога"""

res_df = (pd.DataFrame(results)
          .drop_duplicates(subset=["model"], keep="last")
          .set_index("model"))

print("ИТОГОВАЯ ТАБЛИЦА ВСЕХ МОДЕЛЕЙ")
print(res_df.to_string())

best_name = res_df["PR_AUC"].idxmax()
best_m, best_Xte = models[best_name]
y_prob = best_m.predict_proba(best_Xte)[:,1]

print(f"\n Лучшая модель (по PR-AUC): {best_name}")
print(f"   ROC-AUC = {roc_auc_score(y_te, y_prob):.4f}")
print(f"   PR-AUC  = {average_precision_score(y_te, y_prob):.4f}")

print(f"\nClassification Report ({best_name}, порог 0.5):")
print(classification_report(y_te, (y_prob>=0.5).astype(int),
      target_names=["Остался","Уволится"], zero_division=0))

# F1-оптимальный порог
thresholds = np.linspace(0.01, 0.99, 300)
f1s = [f1_score(y_te, (y_prob>=t).astype(int), zero_division=0) for t in thresholds]
opt_thr = float(thresholds[int(np.argmax(f1s))])
pred_opt = (y_prob >= opt_thr).astype(int)

print(f"F1-оптимальный порог: {opt_thr:.3f}")
print(f"При пороге {opt_thr:.3f}:")
print(classification_report(y_te, pred_opt,
      target_names=["Остался","Уволится"], zero_division=0))

plt.figure(figsize=(6, 5))
cm = confusion_matrix(y_te, pred_opt)
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Pred: остался","Pred: уволится"],
            yticklabels=["Fact: остался","Fact: уволится"])
plt.title(f"{best_name}, порог F1-опт={opt_thr:.3f}")
plt.tight_layout()
plt.show()

"""## 10. ROC и Precision-Recall кривые"""

top_models = res_df.sort_values("PR_AUC", ascending=False).head(4).index.tolist()

plt.figure(figsize=(8, 6))
for name in top_models:
    m, Xte = models[name]
    prob = m.predict_proba(Xte)[:,1]
    fpr, tpr, _ = roc_curve(y_te, prob)
    plt.plot(fpr, tpr, lw=1.8, label=f"{name}: AUC={roc_auc_score(y_te,prob):.3f}")
plt.plot([0,1],[0,1],"k--",lw=1)
plt.xlabel("FPR"); plt.ylabel("TPR"); plt.title("ROC-кривые лучших моделей")
plt.legend(fontsize=9); plt.grid(True, alpha=0.3)
plt.show()

plt.figure(figsize=(8, 6))
for name in top_models:
    m, Xte = models[name]
    prob = m.predict_proba(Xte)[:,1]
    prec, rec, _ = precision_recall_curve(y_te, prob)
    plt.plot(rec, prec, lw=1.8, label=f"{name}: PR-AUC={average_precision_score(y_te,prob):.3f}")
plt.axhline(y_te.mean(), color="black", ls="--", lw=1, label=f"Baseline={y_te.mean():.3f}")
plt.xlabel("Recall"); plt.ylabel("Precision"); plt.title("Precision-Recall кривые лучших моделей")
plt.legend(fontsize=9); plt.grid(True, alpha=0.3)
plt.show()

"""## 11. Интерпретация модели: Feature Importance + SHAP

`feature_importances_` показывает частоту использования признака при разбиении
деревьев. SHAP (TreeExplainer) — более глубокая интерпретация: оценивает
индивидуальный вклад каждого признака в каждое предсказание, с учётом знака влияния.
"""

fi = pd.Series(best_m.feature_importances_, index=FEAT).sort_values(ascending=False)
print(f"Топ-20 признаков по feature_importances_ ({best_name}):")
print(fi.head(20).round(6).to_string())

plt.figure(figsize=(10, 8))
top20 = fi.head(20)
plt.barh(range(len(top20)), top20.values[::-1], color="#2E6DA4")
plt.yticks(range(len(top20)), top20.index[::-1], fontsize=8)
plt.xlabel("Importance"); plt.title(f"Feature Importance: {best_name}")
plt.grid(True, axis="x", alpha=0.3)
plt.tight_layout()
plt.show()

SHAP_N = min(2000, len(best_Xte))
idx_sh = np.random.choice(len(best_Xte), SHAP_N, replace=False)
X_shap = best_Xte.iloc[idx_sh].reset_index(drop=True)

explainer = shap.TreeExplainer(best_m)
shap_values = explainer.shap_values(X_shap)
sv = shap_values[1] if isinstance(shap_values, list) else shap_values

mean_shap = pd.Series(np.abs(sv).mean(axis=0), index=FEAT).sort_values(ascending=False)
print(f"Топ-20 признаков по mean(|SHAP|):")
print(mean_shap.head(20).round(6).to_string())

shap.summary_plot(sv, X_shap, feature_names=FEAT, max_display=20)

"""## 12. HR-скоринг: список сотрудников в зоне риска

Главный продукт для HR-специалиста: таблица сотрудников с вероятностью
увольнения и категорией риска, отсортированная по убыванию.
"""

RISK_THRESHOLD = opt_thr

hr_score = pd.DataFrame({
    "risk_prob": y_prob,
    "risk_category": pd.cut(y_prob,
        bins=[0, RISK_THRESHOLD*0.3, RISK_THRESHOLD, min(RISK_THRESHOLD*2,0.999), 1.0],
        labels=["Низкий","Умеренный","Высокий","Критический"], include_lowest=True),
    "in_risk_zone": (y_prob >= RISK_THRESHOLD).astype(int),
    "actual": y_te.values,
})

n_risk  = hr_score["in_risk_zone"].sum()
n_found = hr_score[(hr_score["in_risk_zone"]==1) & (hr_score["actual"]==1)].shape[0]
n_pos   = hr_score["actual"].sum()

print(f"Порог риска: {RISK_THRESHOLD:.3f}")
print(f"Всего сотрудников в тест-выборке: {len(hr_score):,}")
print(f"В зоне риска: {n_risk:,} ({n_risk/len(hr_score)*100:.1f}%)")
print(f"Реально уволившихся: {n_pos:,}")
print(f"Найдено моделью: {n_found:,} ({n_found/max(n_pos,1)*100:.1f}% от реально уволившихся)")
print(f"\nРаспределение по категориям:")
print(hr_score["risk_category"].value_counts().to_string())

fig, axes = plt.subplots(1, 2, figsize=(13, 4))
hr_score["risk_prob"].hist(bins=60, ax=axes[0], color="#2E6DA4", edgecolor="white")
axes[0].axvline(RISK_THRESHOLD, color="red", ls="--", label=f"Порог {RISK_THRESHOLD:.3f}")
axes[0].set(title="Распределение вероятностей риска", xlabel="P(увольнения)")
axes[0].legend()

cats = ["Низкий","Умеренный","Высокий","Критический"]
hr_score["risk_category"].value_counts().reindex(cats).plot(
    kind="bar", ax=axes[1], color=["#27AE60","#F39C12","#E74C3C","#922B21"], edgecolor="white")
axes[1].set(title="Категории риска"); axes[1].tick_params(axis="x", rotation=15)
plt.tight_layout()
plt.show()

print("\nТоп-15 сотрудников по риску увольнения:")
print(hr_score.sort_values("risk_prob", ascending=False).head(15).round(4).to_string())

"""## 13. Итоговые выводы

### Качество моделей
Лучшая модель LightGBM_SMOTE
- ROC-AUC = 0.6995
- PR-AUC  = 0.0197

Модель пригодна как инструмент
**риск-скоринга и ранжирования** сотрудников, а не точного предсказания.

### Ключевые факторы риска (по SHAP)
1. **Стаж сотрудника** — вероятность увольнения монотонно убывает с ростом стажа
2. **Сезонность** (month, week_of_year) — аномальные пики в январе-феврале
3. **Эффект домино** (colleagues_fired_last_4w) — увольнения коллег повышают риск
4. **Возрастные разрывы с руководителями** (gap_fr_age, gap_ar_age)
5. **Amount-признаки** — несмотря на отсутствие расшифровки, несколько входят в топ предикторов

### Ограничения
- Time-based split при наличии аномальных пиков в начале периода создаёт риск
  смещения оценки, если эти недели концентрируются в train или test
- Переобучение ансамблевых методов (большой разрыв Train/Test AUC) из-за высокой
  размерности признаков относительно числа положительных примеров
- amount_* без содержательного описания — интерпретация ограничена
- Модель не различает добровольные и вынужденные увольнения
- Период наблюдения — один календарный год; необходим регулярный мониторинг
  и переобучение при использовании в продакшене
"""